experiment:
  name: m2beamllm_gps_no_kd
  task: gps
data:
  dataset:
    use_gps: true
    gps_input_size: 2
    gps_feature_mode: m2beamllm_minmax
    gps_normalize: true
model:
  teacher:
    type: m2beamllm_gps_teacher
    gps_input_size: 2
    feature_size: 64
    num_classes: 64
    gru_params: [64, 64, 1]
  student:
    type: m2beamllm_gps_student
    gps_input_size: 2
    feature_size: 64
    num_classes: 64
    gru_params: [64, 64, 1]
distillation:
  type: no_kd
  teacher_model_name: null
output:
  run_name: m2beamllm_gps_no_kd
