experiment:
  name: m2beamllm_image_no_kd
  task: image
model:
  teacher:
    type: m2beamllm_image_teacher
    image_channels: 1
    image_channel_adapter: repeat
    m2beamllm_pretrained: false
    feature_size: 64
    num_classes: 64
    gru_params: [64, 64, 1]
  student:
    type: m2beamllm_image_student
    image_channels: 1
    image_channel_adapter: repeat
    m2beamllm_pretrained: false
    feature_size: 64
    num_classes: 64
    gru_params: [64, 64, 1]
distillation:
  type: no_kd
  teacher_model_name: null
output:
  run_name: m2beamllm_image_no_kd
