experiment:
  name: m2beamllm_radar_no_kd
  task: radar
model:
  teacher:
    type: m2beamllm_radar_teacher
    radar_channels: 2
    radar_input_mode: ra_map
    feature_size: 64
    num_classes: 64
    gru_params: [64, 64, 1]
  student:
    type: m2beamllm_radar_student
    radar_channels: 2
    radar_input_mode: ra_map
    feature_size: 64
    num_classes: 64
    gru_params: [64, 64, 1]
distillation:
  type: no_kd
  teacher_model_name: null
output:
  run_name: m2beamllm_radar_no_kd
