preprocessing:
  type: lidar_bev_cache
  csv_paths:
    - dataset/MMW/sunny/Prepared/Town03_5wayroad_seed28/splits/all_sequences.csv
    - dataset/MMW/sunny/Prepared/Town03_Tjunction_wiz_slope_seed42/splits/all_sequences.csv
    - dataset/MMW/sunny/Prepared/Town03_crossroad_wiz_slope_seed42/splits/all_sequences.csv
    - dataset/MMW/sunny/Prepared/Town03_gastation_seed40/splits/all_sequences.csv
    - dataset/MMW/sunny/Prepared/Town03_roundabout_seed42/splits/all_sequences.csv
  data_root: dataset/MMW/sunny
  cache_dir: outputs/cache/MMW/sunny/lidar_bev
  lidar_prefix: lidar
  bev_size: [224, 224]
  roi: [-30.0, 30.0, -30.0, 30.0, -3.0, 5.0]
  remove_ground: false
  ground_z_threshold: 0.1
  overwrite: false
  progress: true
  cache_version: v1
