preprocessing:
  type: radar_fft_csv
  csv_path: dataset/scenario31/scenario31.csv
  data_root: dataset/scenario31
  output_suffix: DA
  test_mode: false
  test_portion: 0.1
  fft_tuple: [64, 256, 128]

