preprocessing:
  type: radar_fft_csv
  csv_path: dataset/scenario9/scenario9.csv
  data_root: dataset/scenario9
  output_suffix: RA
  test_mode: false
  test_portion: 0.1
  fft_tuple: [64, 256, 128]

