_base_: main_v3_strong_reliability_proto.yaml
experiment:
  name: main_v3_strong_reliability_proto_fullaux
training:
  use_full_aux_loss: true
  lambda_full_aux: 0.3
  full_aux_proto: false
output:
  run_name: main_v3_strong_reliability_proto_fullaux
