"""Default configuration migrated from the original argparse scripts."""

from __future__ import annotations

DEFAULT_CONFIG = {
    "experiment": {
        "name": "kd_sensing",
        "task": "image",
        "seed": 42,
        "device": "auto",
    },
    "paths": {
        "data_root": "dataset/scenario31",
        "output_dir": "outputs",
    },
    "data": {
        "cache": {
            "policy": "auto",
            "lidar": {
                "policy": None,
            },
        },
        "dataset": {
            "type": "deepsense6g",
            "scene": 31,
            "scene_id": 31,
            "scene_slug": "scene31",
            "data_root": None,
            "train_csv_name": None,
            "test_csv_name": None,
            "seq_len": 8,
            "num_pred": 3,
            "portion": 1.0,
            "portion_strategy": "even",
            "portion_seed": 42,
            "image_size": [224, 224],
            "fft_tuple": [64, 256, 128],
            "clipped_range": 128,
            "beam_label_cache": "lazy",
            "use_mmwave": False,
            "mmwave_normalize": True,
            "use_lidar": False,
            "lidar_bev_size": [224, 224],
            "lidar_roi": [-30.0, 30.0, -30.0, 30.0, -3.0, 5.0],
            "lidar_fov_degrees": None,
            "lidar_remove_ground": False,
            "lidar_ground_z_threshold": 0.1,
            "lidar_background_path": None,
            "lidar_background_distance_threshold": 0.2,
            "lidar_cache_dir": "lidar_bev_cache",
            "lidar_use_cache": None,
            "lidar_write_cache": None,
            "lidar_normalize": False,
            "lidar_normalization": None,
            "lidar_memory_cache": False,
            "lidar_augment": False,
            "lidar_point_dropout": 0.0,
            "lidar_jitter_std": 0.0,
        },
        "dataloader": {
            "train_batch_size": 32,
            "test_batch_size": 32,
            "num_workers": 4,
            "pin_memory": True,
            "persistent_workers": True,
            "prefetch_factor": 1,
            "train_drop_last": False,
            "test_drop_last": False,
        },
    },
    "model": {
        "feature_size": 64,
        "d_model": 64,
        "gru_hidden_size": 64,
        "mmwave_input_size": 64,
        "num_classes": 64,
        "seq_length_teacher": 8,
        "seq_length_student": 8,
        "num_pred": 3,
        "downsample_ratio": 1,
        "teacher": {
            "type": "modular_sequence",
            "modalities": ["image"],
            "image_profile": "rgb_imagenet",
            "feature_size": 64,
            "d_model": 64,
            "num_classes": 64,
            "num_pred": 3,
            "encoders": {
                "image": {
                    "type": "resnet18_imagenet_rgb",
                    "output_dim": 64,
                    "pretrained": True,
                    "weights": "DEFAULT",
                    "freeze_backbone": True,
                    "unfreeze_stages": ["layer4"],
                    "dropout": 0.1,
                },
            },
            "representation_core": {
                "type": "single_gru",
                "d_model": 64,
                "hidden_size": 64,
                "num_layers": 1,
            },
            "heads": {
                "beam": {
                    "type": "beam_head",
                    "dropout": 0.1,
                },
            },
        },
        "student": {
            "type": "modular_sequence",
            "modalities": ["image"],
            "image_profile": "rgb_imagenet",
            "feature_size": 64,
            "d_model": 64,
            "num_classes": 64,
            "num_pred": 3,
            "encoders": {
                "image": {
                    "type": "resnet18_imagenet_rgb",
                    "output_dim": 64,
                    "pretrained": True,
                    "weights": "DEFAULT",
                    "freeze_backbone": True,
                    "unfreeze_stages": ["layer4"],
                    "dropout": 0.1,
                },
            },
            "representation_core": {
                "type": "single_gru",
                "d_model": 64,
                "hidden_size": 64,
                "num_layers": 1,
            },
            "heads": {
                "beam": {
                    "type": "beam_head",
                    "dropout": 0.1,
                },
            },
        },
    },
    "loss": {
        "type": "focal_loss",
        "alpha": 1,
        "gamma": 2,
        "beam_soft": {
            "enabled": False,
            "weight": 0.0,
            "sigma": 2.0,
            "circular": True,
            "ignore_index": -100,
        },
        "unimodal_aux": {
            "weight": 0.0,
            "weight_warmup": None,
            "weight_after_warmup": None,
            "ignore_index": -100,
        },
        "gate_weight": 0.0,
        "gate_ramp_epochs": 0,
        "uni_weight_warmup": None,
        "uni_weight_after_warmup": None,
        "prior_regularization": {
            "enabled": False,
            "weight": 0.0,
            "loss_type": "mse",
        },
    },
    "distillation": {
        "type": "no_kd",
        "temperature": 3.0,
        "alpha": 0.4,
        "alpha_warmup_epochs": 0,
        "teacher_model_name": None,
        "rkd_pairs_per_anchor": 4,
        "rkd_distance_weight": 50.0,
        "rkd_angle_weight": 50.0,
    },
    "training": {
        "epochs": 100,
        "warmup_epochs": 0,
        "lr": 1e-3,
        "weight_decay": 0.0,
        "grad_clip": 10.0,
        "patience": 20,
        "use_early_stopping": True,
        "early_stopping_metric": "val_adba",
        "early_stopping_mode": "max",
        "min_delta": 1e-4,
        "resume": False,
        "start_epoch": 0,
        "transfer": {
            "non_blocking": True,
        },
        "amp": {
            "enabled": False,
            "dtype": "float16",
            "grad_scaler": True,
        },
        "modality_dropout": {
            "enabled": False,
            "drop_prob": 0.0,
            "min_keep": 1,
        },
        "counterfactual": {
            "enabled": False,
            "mode": "sample_one",
            "start_epoch": 0,
            "weight": 0.0,
            "target_temperature": 1.0,
            "ignore_delta_eps": 0.0,
            "use_ce_only": True,
            "num_drop_per_batch": 1,
            "min_keep": 1,
            "no_grad_drop_forward": True,
        },
        "reliability_kd": {
            "enabled": False,
            "weight": 0.0,
            "temperature": 3.0,
            "use_modalities": ["gps", "mmwave"],
        },
    },
    "teacher": {
        "registry_path": None,
        "load_encoders": False,
        "freeze_encoders": False,
        "strict": True,
    },
    "finetune": {
        "enabled": False,
        "checkpoint_path": None,
        "strict": True,
        "unfreeze_modalities": [],
        "freeze_modalities": [],
        "param_groups": {
            "enabled": False,
            "fusion_lr": 7.5e-4,
            "head_lr": 7.5e-4,
            "gate_lr": 7.5e-4,
            "strong_encoder_lr": 1.0e-4,
            "weak_encoder_lr": 2.5e-5,
            "strong_modalities": ["gps", "mmwave"],
        },
    },
    "scheduler": {
        "type": "cosine_warm_restarts",
        "T_0": 10,
        "T_mult": 2,
        "eta_min": 1e-6,
    },
    "evaluation": {
        "k_values": [1, 2, 3, 5, 10],
        "dba_delta": 5,
        "record_latency": False,
        "latency_samples_amount": 10,
        "latency_runs": 30,
        "latency_warmup": 5,
        "modality_subsets": {
            "enabled": False,
            "subsets": ["gps", "mmwave", "gps_mmwave", "strong_only", "weak_only", "all"],
        },
    },
    "output": {
        "dir": "outputs",
        "run_name": None,
        "group_by_scene": True,
        "overwrite": False,
        "evaluation_run_name": None,
        "debug": False,
        "tensorboard": {
            "enabled": True,
            "log_dir": "tensorboard",
        },
        "progress": {
            "enabled": True,
        },
    },
    "checkpoint": {
        "strict_load": True,
        "registry": {
            "enabled": True,
            "dir": "outputs/best_checkpoints",
            "prefer": True,
            "metric": "val_top1",
            "filename": "{slug}_{role}_acc_{acc}.pth",
        },
    },
}
