"""Default configuration migrated from the original argparse scripts."""

from __future__ import annotations

DEFAULT_CONFIG = {
    "experiment": {
        "name": "kd_sensing",
        "task": "image",
        "seed": 42,
        "device": "auto",
    },
    "paths": {
        "data_root": "dataset/scenario9",
        "weights_dir": "All_models",
        "output_dir": "outputs",
    },
    "data": {
        "cache": {
            "policy": "auto",
            "image": {
                "policy": None,
            },
            "lidar": {
                "policy": None,
            },
        },
        "dataset": {
            "type": "scenario9",
            "data_root": "dataset/scenario9",
            "train_csv_name": "train_seqs_RA_GPS_LIDAR.csv",
            "test_csv_name": "test_seqs_RA_GPS_LIDAR.csv",
            "seq_len": 8,
            "num_pred": 3,
            "portion": 1.0,
            "portion_strategy": "even",
            "portion_seed": 42,
            "image_size": [224, 224],
            "image_motion_cache_dir": "image_motion_cache",
            "image_motion_use_cache": None,
            "image_motion_write_cache": None,
            "image_motion_cache_version": "v1",
            "image_motion_gaussian_sigma": 1.0,
            "image_motion_threshold_ratio": 0.1,
            "image_motion_threshold_strategy": "relative_max",
            "image_motion_grayscale": "rgb2gray",
            "fft_tuple": [64, 256, 128],
            "clipped_range": 128,
            "beam_label_cache": "lazy",
            "use_mmwave": False,
            "mmwave_normalize": True,
            "use_lidar": False,
            "lidar_bev_size": [224, 224],
            "lidar_roi": [-30.0, 30.0, -30.0, 30.0, -3.0, 5.0],
            "lidar_fov_degrees": None,
            "lidar_remove_ground": False,
            "lidar_ground_z_threshold": 0.1,
            "lidar_background_path": None,
            "lidar_background_distance_threshold": 0.2,
            "lidar_cache_dir": "lidar_bev_cache",
            "lidar_use_cache": None,
            "lidar_write_cache": None,
            "lidar_normalize": False,
            "lidar_normalization": None,
            "lidar_memory_cache": False,
            "lidar_augment": False,
            "lidar_point_dropout": 0.0,
            "lidar_jitter_std": 0.0,
        },
        "dataloader": {
            "train_batch_size": 32,
            "test_batch_size": 32,
            "num_workers": 4,
            "pin_memory": True,
            "persistent_workers": True,
            "prefetch_factor": 1,
            "train_drop_last": False,
            "test_drop_last": False,
        },
    },
    "model": {
        "feature_size": 64,
        "gru_hidden_size": 64,
        "mmwave_input_size": 64,
        "num_classes": 64,
        "seq_length_teacher": 8,
        "seq_length_student": 8,
        "num_pred": 3,
        "downsample_ratio": 1,
        "teacher": {
            "type": "image_teacher",
            "feature_size": 64,
            "num_classes": 64,
            "gru_params": [64, 64, 1],
        },
        "student": {
            "type": "image_student",
            "feature_size": 64,
            "num_classes": 64,
            "gru_params": [64, 64, 1],
        },
    },
    "loss": {
        "type": "focal_loss",
        "alpha": 1,
        "gamma": 2,
    },
    "distillation": {
        "type": "no_kd",
        "temperature": 3.0,
        "alpha": 0.4,
        "alpha_warmup_epochs": 0,
        "teacher_model_name": "ImageTeacher_best.pth",
        "rkd_pairs_per_anchor": 4,
        "rkd_distance_weight": 50.0,
        "rkd_angle_weight": 50.0,
    },
    "training": {
        "epochs": 100,
        "lr": 1e-3,
        "weight_decay": 0.0,
        "grad_clip": 10.0,
        "patience": 20,
        "use_early_stopping": True,
        "min_delta": 1e-4,
        "resume": False,
        "start_epoch": 0,
        "transfer": {
            "non_blocking": True,
        },
        "amp": {
            "enabled": False,
            "dtype": "float16",
            "grad_scaler": True,
        },
    },
    "scheduler": {
        "type": "cosine_warm_restarts",
        "T_0": 10,
        "T_mult": 2,
        "eta_min": 1e-6,
    },
    "evaluation": {
        "k_values": [1, 2, 3, 5, 10],
        "dba_delta": 5,
        "record_latency": False,
        "latency_samples_amount": 10,
        "latency_runs": 30,
        "latency_warmup": 5,
    },
    "output": {
        "dir": "outputs",
        "run_name": None,
        "overwrite": False,
        "evaluation_run_name": None,
        "debug": False,
        "tensorboard": {
            "enabled": True,
            "log_dir": "tensorboard",
        },
        "progress": {
            "enabled": True,
        },
    },
    "checkpoint": {
        "strict_load": True,
        "registry": {
            "enabled": True,
            "dir": "outputs/best_checkpoints",
            "prefer": True,
            "metric": "val_top1",
            "filename": "{slug}_{role}_acc_{acc}.pth",
        },
    },
}
